"""Build WOFF2 shards preserving the reader's Regular/Bold character coverage.

Requires fonttools==4.60.2 and brotli==1.2.0 in an isolated Python environment.
The application build uses the committed output and does not require Python.
"""
from pathlib import Path
import argparse
import re
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
destination = root / "web/src/assets/fonts"
destination.mkdir(parents=True, exist_ok=True)
source_root = root / "web/fonts/source"
weights = {"Regular": 400, "Bold": 700, "Black": 900}
parser = argparse.ArgumentParser()
parser.add_argument("--weights", nargs="+", choices=list(weights), default=list(weights))
selected = set(parser.parse_args().weights)
codepoints = set(TTFont(source_root / "NotoSerifSC-Regular.otf").getBestCmap())
common = set()
# GB2312 一级汉字用于分开常见字与其他字；所有源字形仍完整保留。
for leading in range(0xB0, 0xD8):
    for trailing in range(0xA1, 0xFF):
        try:
            common.add(ord(bytes((leading, trailing)).decode("gb2312")))
        except UnicodeDecodeError:
            pass
latin = {value for value in codepoints if value < 0x3000}
ui = set()
# 将公开首屏的静态用字放在一小片中，避免短标题分散下载多片正文用字。
# 源码变化只影响分组顺序；每次生成仍核对全部字符覆盖。
for relative in ("web/src/pages/Home.tsx", "web/src/components/SiteHeader.tsx",
                 "web/src/components/SiteNotice.tsx", "web/src/components/Layout.tsx",
                 "web/src/components/RouteLoading.tsx", "shared/site-settings.ts"):
    text = (root / relative).read_text()
    text = re.sub(r"/\*.*?\*/|//[^\n]*", "", text, flags=re.S)
    ui.update(ord(character) for character in text if "\u3400" <= character <= "\u9fff")
ui &= codepoints
groups = [sorted(latin), sorted(ui)]
for values in (sorted((common & codepoints) - latin - ui), sorted(codepoints - common - latin - ui)):
    groups.extend(values[start:start + 512] for start in range(0, len(values), 512))

def unicode_range(values):
    ranges = []
    start = end = values[0]
    for value in values[1:]:
        if value == end + 1:
            end = value
        else:
            ranges.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
            start = end = value
    ranges.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
    return ",".join(ranges)

for weight in selected:
    for outdated in destination.glob(f"NotoSerifSC-{weight}-*.woff2"):
        outdated.unlink()
rules = ["/* Generated by scripts/build-reader-fonts.py; Noto Serif SC, SIL OFL 1.1. */"]
for weight in weights:
    source = source_root / f"NotoSerifSC-{weight}.otf"
    original = TTFont(source)
    assert codepoints <= set(original.getBestCmap())
    covered = set()
    total = 0
    for index, values in enumerate(groups):
        output = destination / f"NotoSerifSC-{weight}-{index:02}.woff2"
        if weight in selected:
            font = TTFont(source)
            options = subset.Options()
            options.name_IDs = ["*"]
            options.name_languages = ["*"]
            subsetter = subset.Subsetter(options=options)
            subsetter.populate(unicodes=values)
            subsetter.subset(font)
            font.flavor = "woff2"
            font.save(output)
        converted = TTFont(output)
        assert set(converted.getBestCmap()) == set(values)
        covered.update(converted.getBestCmap())
        for name_id in (0, 13, 14):
            assert converted["name"].getDebugName(name_id) == original["name"].getDebugName(name_id)
        total += output.stat().st_size
        rules.append("@font-face {\n"
                     "  font-family: 'Noto Serif SC';\n  font-style: normal;\n"
                     f"  font-weight: {weights[weight]};\n"
                     "  font-display: swap;\n"
                     f"  src: url('../assets/fonts/{output.name}') format('woff2');\n"
                     f"  unicode-range: {unicode_range(values)};\n}}")
    assert covered == codepoints, "Font conversion changed glyph coverage"
    print(f"{weight}: {source.stat().st_size} -> {total} bytes; {len(covered)} codepoints, {len(groups)} parts")
(root / "web/src/styles/fonts.generated.css").write_text("\n\n".join(rules) + "\n")
