import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ list: vi.fn(), replace: vi.fn(), shelf: vi.fn(), add: vi.fn(), remove: vi.fn(), recent: vi.fn(), removeProgress: vi.fn(), toast: vi.fn(), safeMode: false, user: { id: 'a' } }))
vi.mock('../context/ContentPolicyContext', () => ({ useContentPolicy: () => ({ safeMode: mocks.safeMode }) }))
vi.mock('../lib/api', () => ({ url: (p: string) => p, getToken: () => sessionStorage.getItem('user_session_token') || '', bookmarksApi: { list: mocks.list, replace: mocks.replace }, bookshelfApi: { get: mocks.shelf, add: mocks.add, remove: mocks.remove }, progressApi: { recent: mocks.recent, remove: mocks.removeProgress } }))
vi.mock('../context/SessionContext', () => ({ useSession: () => ({ user: mocks.user, loading: false }) }))
vi.mock('../components/feedback', () => ({ useToast: () => ({ toast: mocks.toast }) }))
import Bookshelf from './Bookshelf'
import { addBookmark, addToBookshelf, getAllBookmarks, getBookshelf, getNovelHistory, saveHistory, setStorageUser } from '../lib/storage'
beforeEach(() => {
  vi.clearAllMocks(); localStorage.clear(); sessionStorage.clear()
  mocks.safeMode = false
  sessionStorage.setItem('user_session_token', 'a'); setStorageUser('a')
  mocks.list.mockResolvedValue({ bookmarks: [] })
  mocks.shelf.mockResolvedValue({ favorites: [], thoughts: [] })
  mocks.recent.mockResolvedValue({ progress: [], tombstones: [] })
})
it('收藏读取第二个云端批次，翻页可以访问第 51 本及第 13 条书签/想法', async () => {
  const favorites = Array.from({ length: 51 }, (_, i) => ({ novelId: `n${i}`, title: `书${i}`, author: '', chapterCount: 1 }))
  const thoughts = Array.from({ length: 13 }, (_, i) => ({ id: `t${i}`, novelId: `n${i}`, chapterId: `c${i}`, thoughtText: `想法${i}`, paragraphIndex: i, createdAt: 1 }))
  mocks.shelf.mockImplementation(({ offset = 0 }) => Promise.resolve({ favorites: favorites.slice(offset, offset + 50), thoughts: thoughts.slice(offset, offset + 50), totals: { favorites: 51, thoughts: 13 } }))
  mocks.list.mockResolvedValue({ bookmarks: Array.from({ length: 13 }, (_, i) => ({ id: `b${i}`, novelId: `n${i}`, novelTitle: `签${i}`, chapterId: `c${i}` })) })
  render(<MemoryRouter><Bookshelf /></MemoryRouter>)
  await screen.findByText(/上次同步/)
  expect(mocks.shelf).toHaveBeenCalledWith({ limit: 50, offset: 50, contentMode: 'adult' })
  for (let i = 0; i < 4; i++) fireEvent.click(screen.getByRole('button', { name: '下一页' }))
  expect(screen.getByText('书50')).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: /书签/ })); fireEvent.click(screen.getByRole('button', { name: '下一页' }))
  expect(screen.getByText('签12')).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: /想法/ })); fireEvent.click(screen.getByRole('button', { name: '下一页' }))
  expect(screen.getByText('想法12').closest('a')).toHaveAttribute('href', '/read/n12/c12?thoughtParagraph=12&thoughtId=t12')
})
it('安全模式请求带筛选，并不展示设备残留的受限阅读记录', async () => {
  mocks.safeMode = true
  saveHistory('restricted', { novelTitle: '受限旧缓存', chapterId: 'c', timestamp: 100 })
  render(<MemoryRouter><Bookshelf /></MemoryRouter>)
  await screen.findByText(/上次同步/)
  expect(mocks.shelf).toHaveBeenCalledWith({ limit: 50, contentMode: 'safe' })
  expect(mocks.list).toHaveBeenCalledWith('safe')
  fireEvent.click(screen.getByRole('button', { name: /最近阅读/ }))
  expect(screen.queryByText('受限旧缓存')).not.toBeInTheDocument()
})
it('进度删除失败保留本机记录，不能提示删除成功', async () => {
  saveHistory('n', { novelTitle: '阅读中的书', chapterId: 'c', timestamp: 100 })
  mocks.removeProgress.mockRejectedValueOnce(new Error('offline'))
  render(<MemoryRouter><Bookshelf /></MemoryRouter>)
  await screen.findByText(/上次同步/)
  fireEvent.click(screen.getByRole('button', { name: /最近阅读/ }))
  fireEvent.click(screen.getByRole('button', { name: '清除记录' }))
  await waitFor(() => expect(mocks.toast).toHaveBeenCalledWith('删除阅读记录失败：offline', 'error'))
  expect(getNovelHistory('n')?.chapterId).toBe('c')
})
it('旧删除请求被服务端跳过时接纳较新位置，保留阅读记录', async () => {
  saveHistory('n', { novelTitle: '阅读中的书', chapterId: 'old', timestamp: 100 })
  mocks.removeProgress.mockResolvedValueOnce({ success: true, skipped: true, progress: { novelId: 'n', chapterId: 'new', scrollPercent: .8, updatedAt: 200 }, tombstone: null })
  render(<MemoryRouter><Bookshelf /></MemoryRouter>)
  await screen.findByText(/上次同步/)
  fireEvent.click(screen.getByRole('button', { name: /最近阅读/ }))
  fireEvent.click(screen.getByRole('button', { name: '清除记录' }))
  await waitFor(() => expect(mocks.toast).toHaveBeenCalledWith('阅读位置已更新，保留较新的记录', 'default'))
  expect(getNovelHistory('n')).toMatchObject({ chapterId: 'new', scrollPercent: .8 })
})
it('打开或手动同步书架只读云端，不回传旧设备收藏或复活书签', async () => {
  addBookmark('old', '旧书签', 'c', '', 1)
  addToBookshelf({ id: 'old', title: '旧收藏', author: '', chapterCount: 1 })
  render(<MemoryRouter><Bookshelf /></MemoryRouter>)
  await screen.findByText(/上次同步/)
  expect(getAllBookmarks()).toEqual([])
  expect(getBookshelf()).toEqual([])
  expect(mocks.replace).not.toHaveBeenCalled()
  expect(mocks.add).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: '立即同步' }))
  await waitFor(() => expect(mocks.list).toHaveBeenCalledTimes(2))
  expect(mocks.replace).not.toHaveBeenCalled()
  expect(mocks.add).not.toHaveBeenCalled()
})
it('云端删除失败时保留收藏并展示错误', async () => {
  mocks.shelf.mockResolvedValue({ favorites: [{ novelId: 'n', title: '云端书', author: '', chapterCount: 1 }], thoughts: [] })
  mocks.remove.mockRejectedValue(new Error('offline'))
  render(<MemoryRouter><Bookshelf /></MemoryRouter>)
  await screen.findByText('云端书')
  fireEvent.click(screen.getByRole('button', { name: '取消收藏' }))
  await waitFor(() => expect(mocks.toast).toHaveBeenCalledWith('offline', 'error'))
  expect(getBookshelf()).toHaveLength(1)
  expect(screen.getByText('云端书')).toBeInTheDocument()
})
